---
# tasks file for k8s-tls

- name: 准备自签证书工具cfssl
  unarchive: src=cfssl.tar.gz dest=/usr/bin/

- name: 获取项目根目录
  shell: pwd | sed 's/roles.*//'
  register: project_dir
- debug: msg={{ project_dir.stdout }}

- name: 创建ssl证书目录结构
  file: path={{ project_dir.stdout }}/ssl/{{ item }} state=directory
  with_items:
    - etcd
    - k8s 

- name: 准备etcd集群ca初始化文件
  copy: src=etcd-ca/{{ item }} dest={{ project_dir.stdout }}/ssl/etcd/{{ item }}
  with_items:
    - ca-csr.json
    - ca-config.json

- name: 准备etcd证书配置文件
  template: src=etcd-csr.json.j2 dest={{ project_dir.stdout }}/ssl/etcd/etcd-csr.json

- name: 开始初始化ca并颁发etcd集群证书
  shell: |
       cd {{ project_dir.stdout }}/ssl/etcd/ 
       cfssl gencert -initca ca-csr.json | cfssljson -bare etcd-ca -
       cfssl gencert -ca=etcd-ca.pem -ca-key=etcd-ca-key.pem -config=ca-config.json -profile=etcd etcd-csr.json | cfssljson -bare etcd-server

- name: 准备kubernetes集群ca初始化文件
  copy: src=k8s-ca/{{ item }} dest={{ project_dir.stdout }}/ssl/k8s/{{ item }}
  with_items:
    - ca-csr.json
    - ca-config.json

- name: 准备kube-apiserver证书配置文件
  template: src=kube-apiserver-csr.json.j2 dest={{ project_dir.stdout }}/ssl/k8s/kube-apiserver-csr.json

- name: 准备kube-proxy证书配置文件
  copy: src=kube-proxy-csr.json dest={{ project_dir.stdout }}/ssl/k8s/kube-proxy-csr.json

- name: 开始初始化ca并颁发kubernetes集群证书
  shell: |
       cd {{ project_dir.stdout }}/ssl/k8s/ 
       cfssl gencert -initca ca-csr.json | cfssljson -bare k8s-ca -
       cfssl gencert -ca=k8s-ca.pem -ca-key=k8s-ca-key.pem -config=ca-config.json -profile=kubernetes kube-apiserver-csr.json | cfssljson -bare kube-apiserver
       cfssl gencert -ca=k8s-ca.pem -ca-key=k8s-ca-key.pem -config=ca-config.json -profile=kubernetes kube-proxy-csr.json | cfssljson -bare kube-proxy
